export const TvShowActionTypes = {
	FETCHING_TV_DETAILS_START: 'FETCHING_TV_DETAILS_START',
	FETCHING_TV_DETAILS_SUCCESS: 'FETCHING_TV_DETAILS_SUCCESS',
	FETCHING_TV_DETAILS_FAILURE: 'FETCHING_TV_DETAILS_FAILURE',

	FETCHING_TV_VIDEOS_START: 'FETCHING_TV_VIDEOS_START',
	FETCHING_TV_VIDEOS_SUCCESS: 'FETCHING_TV_VIDEOS_SUCCESS',
	FETCHING_TV_VIDEOS_FAILURE: 'FETCHING_TV_VIDEOS_FAILURE',

	FETCHING_TV_CASTS_START: 'FETCHING_TV_CASTS_START',
	FETCHING_TV_CASTS_SUCCESS: 'FETCHING_TV_CASTS_SUCCESS',
	FETCHING_TV_CASTS_FAILURE: 'FETCHING_TV_CASTS_FAILURE',
};
