export const SearchActionTypes = {
	SET_QUERY: 'SET_QUERY',
	CLEAR_QUERY: 'CLEAR_QUERY',
	FETCH_SEARCH_RESULTS_START: 'FETCH_SEARCH_RESULTS_START',
	FETCH_SEARCH_RESULTS_SUCCESS: 'FETCH_SEARCH_RESULTS_SUCCESS',
	FETCH_SEARCH_RESULTS_FAILURE: 'FETCH_SEARCH_RESULTS_FAILURE',
	CLEAR_SEARCH_RESULTS: 'CLEAR_SEARCH_RESULTS',
};
