export const MovieActionTypes = {
	FETCHING_MOVIE_DETAILS_START: 'FETCHING_MOVIE_DETAILS_START',
	FETCHING_MOVIE_DETAILS_SUCCESS: 'FETCHING_MOVIE_DETAILS_SUCCESS',
	FETCHING_MOVIE_DETAILS_FAILURE: 'FETCHING_MOVIE_DETAILS_FAILURE',

	FETCHING_MOVIE_VIDEOS_START: 'FETCHING_MOVIE_VIDEOS_START',
	FETCHING_MOVIE_VIDEOS_SUCCESS: 'FETCHING_MOVIE_VIDEOS_SUCCESS',
	FETCHING_MOVIE_VIDEOS_FAILURE: 'FETCHING_MOVIE_VIDEOS_FAILURE',

	FETCHING_MOVIE_CASTS_START: 'FETCHING_MOVIE_CASTS_START',
	FETCHING_MOVIE_CASTS_SUCCESS: 'FETCHING_MOVIE_CASTS_SUCCESS',
	FETCHING_MOVIE_CASTS_FAILURE: 'FETCHING_MOVIE_CASTS_FAILURE',
};
