export const MoviesActionTypes = {
	FETCH_POPULAR_MOVIES_START: 'FETCH_POPULAR_MOVIES_START',
	FETCH_POPULAR_MOVIES_SUCCESS: 'FETCH_POPULAR_MOVIES_SUCCESS',
	FETCH_POPULAR_MOVIES_FAILURE: 'FETCH_POPULAR_MOVIES_FAILURE',

	FETCH_NOW_PLAYING_MOVIES_START: 'FETCH_NOW_PLAYING_MOVIES_START',
	FETCH_NOW_PLAYING_MOVIES_SUCCESS: 'FETCH_NOW_PLAYING_MOVIES_SUCCESS',
	FETCH_NOW_PLAYING_MOVIES_FAILURE: 'FETCH_NOW_PLAYING_MOVIES_FAILURE',

	FETCH_UPCOMMING_MOVIES_START: 'FETCH_UPCOMMING_MOVIES_START',
	FETCH_UPCOMMING_MOVIES_SUCCESS: 'FETCH_UPCOMMING_MOVIES_SUCCESS',
	FETCH_UPCOMMING_MOVIES_FAILURE: 'FETCH_UPCOMMING_MOVIES_FAILURE',

	FETCH_GENRE_START: 'FETCH_GENRE_START',
	FETCH_GENRE_SUCCESS: 'FETCH_GENRE_SUCCESS',
	FETCH_GENRE_FAILURE: 'FETCH_GENRE_FAILURE',
};
