export const TvShowsActionTypes = {
	FETCH_POPULAR_TV_SHOWS_START: 'FETCH_POPULAR_TV_SHOWS_START',
	FETCH_POPULAR_TV_SHOWS_SUCCESS: 'FETCH_POPULAR_TV_SHOWS_SUCCESS',
	FETCH_POPULAR_TV_SHOWS_FAILURE: 'FETCH_POPULAR_TV_SHOWS_FAILURE',

	FETCH_TV_SHOWS_GENRE_START: 'FETCH_TV_SHOWS_GENRE_START',
	FETCH_TV_SHOWS_GENRE_SUCCESS: 'FETCH_TV_SHOWS_GENRE_SUCCESS',
	FETCH_TV_SHOWS_GENRE_FAILURE: 'FETCH_TV_SHOWS_GENRE_FAILURE',
};
